services:
  - type: web
    name: telegram-chatgpt-bot
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        fromDatabase: false
      - key: OPENAI_API_KEY
        fromDatabase: false
    autoDeploy: true