services:
  - type: web
    name: telegram-chatgpt-bot
    env: python
    pythonVersion: "3.12"
    buildCommand: "poetry install --no-root"
    startCommand: "poetry run python bot.py"
    autoDeploy: true