services:
  - type: web
    name: telegram-chatgpt-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        fromDatabase: false
        value: "ВАШ_TELEGRAM_BOT_TOKEN"
      - key: OPENAI_API_KEY
        fromDatabase: false
        value: "ВАШ_OPENAI_API_KEY"
