services:
  - type: web
    name: telegram-chatgpt-bot
    env: docker
    dockerfilePath: ./Dockerfile
    branch: main
    autoDeploy: true
    plan: starter
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_TOKEN
        fromDatabase: false
        value: "ВАШ_ТОКЕН"
      - key: OPENAI_API_KEY
        fromDatabase: false
        value: "ВАШ_ТОКЕН"